global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'springboot_welcome_app'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'otlp_springboot_app'
    static_configs:
      - targets: ['otel-collector:8889']